import { Injectable } from '@angular/core';
import { Foods } from 'src/app/shared/models/food';

@Injectable({
  providedIn: 'root',
})
export class FoodService {
  constructor() {}

  getAll(): Foods[] {
    return [
      {
        id: 1,
        price: 14,
        name: 'special pizza',
        favorite: false,
        star: 4,
        tags: ['pizza', 'lunch', 'fastFood', 'dinner'],
        imageUrl: './assets/food-1.jpg',
        cookTimes: '15-20',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 2,
        price: 11,
        name: 'special burger',
        favorite: true,
        star: 4,
        tags: ['fastFood', 'burger'],
        imageUrl: './assets/food-2.jpg',
        cookTimes: '16-18',
        origin: ['australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 3,
        price: 12,
        name: 'Konkani style',
        favorite: false,
        star: 4,
        tags: ['lunch', 'fastFood', 'dinner'],
        imageUrl: './assets/food-3.jpg',
        cookTimes: '20-25',
        origin: ['south', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 4,
        price: 10,
        name: 'Nacho cheese',
        favorite: false,
        star: 4,
        tags: ['fastFood'],
        imageUrl: './assets/food-4.jpg',
        cookTimes: '20-22',
        origin: ['india', 'australia', 'china', 'russia', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 5,
        price: 10,
        name: 'momos',
        favorite: true,
        star: 4,
        tags: ['fastFood', 'momos'],
        imageUrl: './assets/food-5.jpg',
        cookTimes: '15-20',
        origin: ['india', 'australia', 'china', 'russia', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 6,
        price: 16,
        name: 'Rajasthani plate',
        favorite: false,
        star: 4,
        tags: ['lunch', 'dinner'],
        imageUrl: './assets/food-6.jpg',
        cookTimes: '20-25',
        origin: ['rajasthan', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 7,
        price: 12,
        name: 'amritsar murgh makhani',
        favorite: true,
        star: 4,
        tags: ['fastFood', 'lunch', 'dinner'],
        imageUrl: './assets/food-7.jpg',
        cookTimes: '25-30',
        origin: ['amritsar', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 8,
        price: 11,
        name: 'gujarati pizza',
        favorite: false,
        star: 4,
        tags: ['pizza', 'fastFood', 'lunch', 'dinner'],
        imageUrl: './assets/food-8.png',
        cookTimes: '20-25',
        origin: ['gujarati', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 9,
        price: 11,
        name: 'spicy spaghetti',
        favorite: false,
        star: 4,
        tags: ['fastFood'],
        imageUrl: './assets/food-9.jpg',
        cookTimes: '20-25',
        origin: ['china', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 10,
        price: 11,
        name: 'squid or calamari roast',
        favorite: false,
        star: 4,
        tags: ['fastFood'],
        imageUrl: './assets/food-10.jpg',
        cookTimes: '20-25',
        origin: ['china', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 11,
        price: 12,
        name: 'tacos',
        favorite: false,
        star: 4,
        tags: ['fastFood'],
        imageUrl: './assets/food-11.jpg',
        cookTimes: '20-25',
        origin: ['china', 'australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 12,
        price: 11,
        name: 'Hot burger',
        favorite: false,
        star: 4,
        tags: ['burger', 'fastFood'],
        imageUrl: './assets/food-12.jpg',
        cookTimes: '10-15',
        origin: ['china', 'australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 13,
        price: 12,
        name: 'nacho',
        favorite: false,
        star: 4,
        tags: ['lunch', 'fastFood'],
        imageUrl: './assets/food-13.jpg',
        cookTimes: '15-20',
        origin: ['china', 'australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 14,
        price: 14,
        name: 'Greek-australian',
        favorite: false,
        star: 4,
        tags: ['fastFood'],
        imageUrl: './assets/food-14.jpg',
        cookTimes: '10-15',
        origin: ['australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 15,
        price: 10,
        name: 'burger',
        favorite: false,
        star: 4,
        tags: ['fastFood', 'burger'],
        imageUrl: './assets/food-15.jpg',
        cookTimes: '15-20',
        origin: ['china', 'australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 16,
        price: 14,
        name: 'veg fried rise',
        favorite: true,
        star: 4,
        tags: ['lunch', 'fastFood'],
        imageUrl: './assets/food-16.jpg',
        cookTimes: '20-25',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 17,
        price: 12,
        name: 'special momos',
        favorite: false,
        star: 4,
        tags: ['momos', 'fastFood'],
        imageUrl: './assets/food-17.jpg',
        cookTimes: '20-25',
        origin: ['china', 'australia', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 18,
        price: 10,
        name: 'burger',
        favorite: false,
        star: 4,
        tags: ['burger', 'fastFood'],
        imageUrl: './assets/food-18.jpg',
        cookTimes: '10-15',
        origin: ['china', 'india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 19,
        price: 16,
        name: 'veg thali',
        favorite: true,
        star: 4,
        tags: ['lunch', 'dinner'],
        imageUrl: './assets/food-19.jpg',
        cookTimes: '20-25',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 20,
        price: 16,
        name: 'sweets',
        favorite: false,
        star: 4,
        tags: ['sweets', 'lunch', 'dinner'],
        imageUrl: './assets/food-20.jpg',
        cookTimes: '10-15',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 21,
        price: 16,
        name: 'chhole-bhature',
        favorite: false,
        star: 4,
        tags: ['breakfast', 'lunch', 'dinner', 'chhole-bhature'],
        imageUrl: './assets/food-21.jpg',
        cookTimes: '10-15',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 22,
        price: 16,
        name: 'paranthe-chhole',
        favorite: false,
        star: 4,
        tags: ['paranthe', 'lunch', 'dinner', 'chhole', 'paranthe-chhole'],
        imageUrl: './assets/food-22.jpg',
        cookTimes: '12-15',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 23,
        price: 15,
        name: 'paw-bhaji',
        favorite: true,
        star: 4,
        tags: ['paw-bhaji', 'lunch', 'dinner'],
        imageUrl: './assets/food-23.jpg',
        cookTimes: '14-18',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 24,
        price: 12,
        name: 'kachodi',
        favorite: false,
        star: 4,
        tags: ['kachodi', 'lunch', 'dinner'],
        imageUrl: './assets/food-24.jpg',
        cookTimes: '10-15',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 25,
        price: 16,
        name: 'chhole-kulche',
        favorite: false,
        star: 4,
        tags: ['chhole-kulche', 'lunch', 'dinner'],
        imageUrl: './assets/food-25.jpg',
        cookTimes: '12-17',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 26,
        price: 14,
        name: 'Szechuan',
        favorite: true,
        star: 4,
        tags: ['Szechuan', 'lunch', 'dinner'],
        imageUrl: './assets/food-26.jpg',
        cookTimes: '12-16',
        origin: ['china', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 27,
        price: 18,
        name: 'shahi-tukda',
        favorite: false,
        star: 4,
        tags: ['sweets', 'lunch', 'dinner', 'shahi-tukda'],
        imageUrl: './assets/food-27.jpg',
        cookTimes: '15-19',
        origin: ['hyderabad','india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
      {
        id: 28,
        price: 21,
        name: 'veg-thali',
        favorite: false,
        star: 4,
        tags: ['veg-thali', 'lunch', 'dinner', 'paneer', 'tandoori'],
        imageUrl: './assets/food-28.jpg',
        cookTimes: '18-22',
        origin: ['india', 'asia'],
        addedToCart:false,
        addedCount:0,
      },
    ];
  }
}
